### ISSUE TITLE
[ERROR] No .editorconfig properties applicable for files in a Maven module without .editorconfig

### ISSUE THREAD

**Issue by ppalaga** [ec4j/editorconfig-maven-plugin#11]
When building in a module directory of a multimodule Maven project, the `.editorconfig` file in the root of the source tree is not seen. Something like the following is logged:

```
[ERROR] No .editorconfig properties applicable for files under ...
```

**Comment by flod1** [comment]
on windows, i have a .editorconfig file in the root folder, but the error message come again. :-(

**Comment by ppalaga** [comment]
@flod1 could you please open a new issue with proper steps to reproduce?
