### ISSUE TITLE
Link to central.maven.org unreachable

### ISSUE THREAD

**Issue by BaumiCoder** [ec4j/editorconfig-maven-plugin#140]
In the example snipped for the pom.xml there is a link where to find the actual version:
http://central.maven.org/maven2/org/ec4j/maven/editorconfig-maven-plugin

That server is not reachable anymore. I am new to maven, so I don't know what it had look like on central.maven.org.
Maybe this would be the actual version of that link:
https://central.sonatype.com/artifact/org.ec4j.maven/editorconfig-maven-plugin
(maven.org redirects to central.sonatype.com)

**Comment by Oliver-Loeffler** [comment]
Instead of "central", "search" is the right word.

This one works:
http://search.maven.org/maven2/org/ec4j/maven/editorconfig-maven-plugin
