### ISSUE TITLE
Question: How can I run the formatter on Maven sub projects?

### ISSUE THREAD

**Issue by Oliver-Loeffler** [ec4j/editorconfig-maven-plugin#155]
Hello,

I am experimenting with this plugin. It is nicely detecting rule violations in the root of a project (e.g. in POM.xml) but it is not detecting violations in Java files.

The exemple project is this one:
https://github.com/Oliver-Loeffler/scenebuilder/tree/issue-485-demo

What would be the right way to configure the plugin and to run the plug in order to detect and correct format violations in Java sources as well? I was playing with many different settings the last days but nothing worked like expected - however, my expectation can be wrong as well.

I was using:

```shell
mvn editorconfig:check
mvn editorconfig:format
```

with the following config:
```ini
# EditorConfig is awesome: https://EditorConfig.org
root = true

[*.java]
indent_style = space
indent_size = 4

[*.fxml]
indent_style = space
indent_size = 2

[*.yml]
indent_style = space
indent_size = 2

[pom.xml]
indent_style = space
indent_size = 4
```

The source file `app\src\main\java\com\oracle\javafx\scenebuilder\app\AppPlatform.java` is full of tabs and I'd expect a complaint/violation for this file. It works well with the main (reactor) `POM.xml` but not with any of the sources.

The plugin is configured like:
```xml
    <build>
        <pluginManagement>
            <plugin>
                    <groupId>org.ec4j.maven</groupId>
                    <artifactId>editorconfig-maven-plugin</artifactId>
                    <version>0.1.3</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
               <plugin>
                    <groupId>org.ec4j.maven</groupId>
                    <artifactId>editorconfig-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>check</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
        <plugins>
    </build>
```

Thanks in advance!
Oliver

**Comment by ppalaga** [comment]
Thanks for the report @Oliver-Loeffler 

> What would be the right way to configure the plugin and to run the plug in order to detect and correct format violations in Java sources as well?

No way for the indentation unfortunately, see https://github.com/ec4j/editorconfig-linters/issues/23

As hinted around here: https://github.com/ec4j/editorconfig-maven-plugin?tab=readme-ov-file#how-it-works java files are currenly handled only by the TextLinter which supports only end_of_line, trim_trailing_whitespace and insert_final_newline

It is the same for YAML.

If fxml is XML, then you can map it to XMLLinter using the [linters](https://github.com/ec4j/editorconfig-maven-plugin/blob/main/editorconfig-maven-plugin/src/main/java/org/ec4j/maven/AbstractEditorConfigMojo.java#L158) config option, something like 

```xml
      <plugin>
        <groupId>org.ec4j.maven</groupId>
        <artifactId>editorconfig-maven-plugin</artifactId>
        <version>...</version>
        <configuration>
          <linters>
            <linter>
              <className>org.ec4j.linters.XmlLinter</className>
              <includes>
                <include>**/*.fxml</include>
              </includes>
            </linter>
          </linters>
        </configuration>
      </plugin>
```

**Comment by Oliver-Loeffler** [comment]
Hello @ppalaga ,
thanks for the swift explanation. I was just not sure if this is still the recent state. Thank you for clarification. Also thanks for pointing out how to possibly format the FXML file. This is something worth to consider. As of this moment, the checkstyle plugin and the editorconfig-maven-plugin could complement each other.
