### ISSUE TITLE
Invalid editorconfig.excludes throw NullPointerException

### ISSUE THREAD

**Issue by mhagnumdw** [ec4j/editorconfig-maven-plugin#22]
If run

`mvn org.ec4j.maven:editorconfig-maven-plugin:check -Deditorconfig.excludes="db/**,log/**,hibernate.properties,"`

whith a `,` at the end, throw an NullPointerException in `org.ec4j.maven.AbstractEditorconfigMojo.scanIncludedFiles(AbstractEditorconfigMojo.java:316)`

Maybe validating the input and throwing a more user friendly message is better.

**Comment by ppalaga** [comment]
Fixed in the just released version 0.0.11. Thanks again for the report.
