### ISSUE TITLE
.editorconfig file not found windows 10

### ISSUE THREAD

**Issue by flod1** [ec4j/editorconfig-maven-plugin#26]
[WARNING] Using current platform's default encoding UTF-8 to read .editorconfig files. You do not want this. Set either 'project.build.sourceEncoding' or 'editorconfig.encoding' property.
[ERROR] No .editorconfig properties applicable for files under 'C:\Projects\web\assembly\minuteProject'

i have  .editorconfig file next pom.xml but the maven plugoin didn't found the editorconfig file :-(

**Comment by ppalaga** [comment]
Could you please share your project?

**Comment by svanteschubert** [comment]
I am using .editorconfig in a Windows10 Java environment and it works fine:
https://github.com/tdf/odftoolkit/compare/issue-15

PS: Only strange that although tabs are being used close to everywhere within the XML (see pom.xml file), there are still spaces in front of XML comments and obviously no intent for those.

**Comment by ppalaga** [comment]
> [ERROR] No .editorconfig properties applicable for files under 'C:\Projects\web\assembly\minuteProject'

The message rather sounds like there are no files in your project that would match the selectors and properties in your `.editorconfig` file.

Closing for now. If the problem persists, please share a project where the behavior can be reproduced.
