### ISSUE TITLE
Mark mojos as threadSafe

### ISSUE THREAD

**Issue by fschrogl** [ec4j/editorconfig-maven-plugin#39]
Both Mojos use the default setting of `threadSafe = false`, resulting in warnings when the plugin is used in parallel Maven builds.

According to [SO: Maven Thread Safe Plugin Pitfalls](https://stackoverflow.com/questions/22133520/maven-thread-safe-plugin-pitfalls) a Mojo should basically be thread-safe if its instantiation strategy is `per-lookup` and it doesn't use static variables.

This is true for both Mojos. So would it be sufficient to just set `threadSafe = true` in both Mojos to get rid of the warnings?

**Comment by ppalaga** [comment]
Thanks for the proposal, it sounds reasonable. A PR is welcome but it would be nice if you could also provide a test - see https://github.com/ec4j/editorconfig-maven-plugin/blob/master/editorconfig-maven-plugin/src/test/java/org/ec4j/maven/EditorConfigMojosTest.java#L41 and https://github.com/ec4j/editorconfig-maven-plugin/tree/master/editorconfig-maven-plugin/src/test/projects for examples.

**Comment by ppalaga** [comment]
Fixed in the just released version 0.0.11. Thanks again for the proposal.
