### ISSUE TITLE
Links in the README broken after moving the linters to a separate git repo

### ISSUE THREAD

**Issue by derTobsch** [ec4j/editorconfig-maven-plugin#40]
Hey, first of all great to see a maven plugin for editorconfig. We will use it here 
https://github.com/synyx/urlaubsverwaltung - a pr is open now :)

The link in the readme gives me a 404.
https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-lint-api/src/main/java/org/ec4j/maven/lint/api/Constants.java#L37

**Comment by ppalaga** [comment]
Thanks for the report. Yes, some refactoring happened. Let me fix it.

**Comment by ppalaga** [comment]
Took some time to fix, but thanks for the report anyway!
