### ISSUE TITLE
Wrong tab indentation with XML linter

### ISSUE THREAD

**Issue by akersch** [ec4j/editorconfig-maven-plugin#58]
When using the XML linter and tab indentation one gets wrong indentation handling.

Editorconfig:

```
[*.{xml}]
indent_style = tab
indent_size = tab
tab_width = 4
```

The result is, that the Editorconfig Maven Plugin demands for each indentation level 4 tabs, for example for 2 indentations then 8 tabs. This is also the case when setting indent_size=4 and omitting tab_width.

What works, but this is not conforming to Editorconfig:

```
[*.{xml}]
indent_style = tab
indent_size = 1
tab_width = 4
```
Then the plugin uses 1 tab for indentation. But IDEs like Intellij then set indent size to 1 character and ignore the tab width.

The spec on editorconfig.org states:

* indent_style: set to tab or space to use hard tabs or soft tabs respectively.
* indent_size: a whole number defining the number of columns used for each indentation level and the width of soft tabs (when supported). When set to tab, the value of tab_width (if specified) will be used.
* tab_width: a whole number defining the number of columns used to represent a tab character. This defaults to the value of indent_size and doesn't usually need to be specified

**Comment by akersch** [comment]
Additionally: the text linter works correctly with the settings above, only the XML linter does not work.

**Comment by ppalaga** [comment]
Thanks for the report, @akersch. Would you mind writing a new test case in [XmlLinterTest](https://github.com/ec4j/editorconfig-linters/blob/master/editorconfig-linters/src/test/java/org/ec4j/linters/XmlLinterTest.java) that reproduces this issue?

**Comment by ppalaga** [comment]
The fix is merged in the master of the linters project. I'd release the linters and maven plugin unless you have more reports/fixes?

**Comment by ppalaga** [comment]
Fixed via https://github.com/ec4j/editorconfig-linters/pull/21

**Comment by akersch** [comment]
> The fix is merged in the master of the linters project. I'd release the linters and maven plugin unless you have more reports/fixes?

Currently, I do not have more reports. 

Thank you for the fast fix!

**Comment by ppalaga** [comment]
Version 0.1.1 of editorconfig-maven-plugin was released.
